simple_project_docs/project/urls.py
from django.conf.urls.defaults import patterns, include, url

from django.views.generic.simple import direct_to_template

from django.views.generic import list_detail
from project.views import project_detail
from project.models import Project


project_info = {
    "queryset" : Project.objects.all(),
        "template_object_name" : "project",
}

urlpatterns = patterns('',
    url(r'^list/$', list_detail.object_list, project_info, name='project_list'),#, {'template_name':'project/project_list.html'}),
    url(r'^detail/(?P<project_id>\d+)/$', project_detail, name='project_detail'),
    #, {'template': 'onesheet.html'}),
)

"""
urlpatterns = patterns('',
    (r'^list/$',             direct_to_template, {'template': 'project_index.html'}),
    (r'^detail/(?P<id>\d+)/$', direct_to_template, {'template': 'onesheet.html'}),
)
"""

simple_project_docs/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'simple_project_docs.views.home', name='home'),
    url(r'^project/', include('simple_project_docs.project.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls), name='django_admin'),


)

if settings.DEBUG:
    urlpatterns += patterns('',
# (r'^static-mcb/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
 (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

simple_project_docs/project/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse

PROJECT_UPLOAD_DIR = 'project_docs'

class AuthSystem(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(blank=True)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ('name', )

class Server(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(blank=True)
    short_description = models.CharField(max_length=255)
    description = models.TextField(blank=True)
 
    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ('name', )


class ProjectStatus(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'Project Statuses'

class ProjectTag(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(blank=True)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ('name', )
    
class Database(models.Model):
    name = models.CharField(max_length=255, help_text='Reference, not actual db_name')
    db_name = models.CharField('Database Name', max_length=255)
    server = models.ForeignKey(Server, on_delete=models.PROTECT)
    description = models.CharField(max_length=255)
    db_user = models.CharField('Database User', max_length=255, blank=True, help_text='optional')

    def __unicode__(self):
        return '%s, %s - %s' % (self.name, self.db_name, self.server)
        
    class Meta:
        ordering = ('name', )

class Project(models.Model):
    name = models.CharField(max_length=255)
    status = models.ForeignKey(ProjectStatus, on_delete=models.PROTECT)
    is_live = models.BooleanField(default=False)
    slug = models.SlugField(max_length=255, blank=True)
    purpose = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    contacts = models.TextField()

    url = models.URLField(blank=True)
    codebase = models.TextField(blank=True)
    authentication = models.ManyToManyField(AuthSystem, blank=True, null=True)
    servers = models.ManyToManyField(Server, blank=True, null=True)
    databases = models.ManyToManyField(Database, blank=True, null=True)
    
    related_projects = models.ManyToManyField('self', related_name='related projects', blank=True, null=True)
    tags = models.ManyToManyField(ProjectTag, blank=True, null=True)
    
    last_update = models.DateTimeField(auto_now=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return self.name
    

    def get_project_docs(self):
        return ProjectDoc.objects.filter(project=self).all()

    def has_project_docs(self):
        if ProjectDoc.objects.filter(project=self).count() > 0:
            return True
        return False
        
    def get_project_links(self):
        return ProjectLink.objects.filter(project=self).all()
      
    def has_project_links(self):
        if ProjectLink.objects.filter(project=self).count() > 0:
            return True
        return False
         
    def get_html_filename(self):
        if not self.slug:
            return None
        return '%s.html' % self.slug
    
    def get_absolute_url(self):
        if self.id:
                return reverse('project_detail', kwargs={ 'project_id' : self.id })
        return ''
            
    def save(self):
        if self.id is None:
            super(Project, self).save()
            
        self.slug = slugify(self.name)
        while 1:
            if Project.objects.exclude(id=self.id).filter(slug=self.slug).count() > 0:
                self.slug = self.slug + '_'
            else:
                break
                
        super(Project, self).save()
        
        
    class Meta:
        ordering = ('name', )

class ProjectDoc(models.Model):
    project = models.ForeignKey(Project, on_delete=models.PROTECT)
    name = models.CharField(max_length=255)
    doc = models.FileField(upload_to=PROJECT_UPLOAD_DIR)
    sort_order = models.IntegerField(default=1)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('project', 'sort_order' )

class ProjectLink(models.Model):
    project = models.ForeignKey(Project, on_delete=models.PROTECT)
    name = models.CharField(max_length=255)
    url = models.URLField(verify_exists=False)
    sort_order = models.IntegerField(default=1)

    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ('project', 'sort_order' )

    
class ProjectNote(models.Model):
    project = models.ForeignKey(Project, on_delete=models.PROTECT)
    note = models.TextField()
    
    last_update = models.DateTimeField(auto_now=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('last_update', 'project' )

simple_project_docs/project/views.py
from django.views.generic import list_detail
from django.shortcuts import get_object_or_404
from project.models import Project

def project_detail(request, project_id):
    # Look up the Author (and raise a 404 if she's not found)
    project = get_object_or_404(Project, pk=project_id)
    print 'project_detail', project
    # Show the detail page
    return list_detail.object_detail(
        request,
        queryset = Project.objects.all(),
        object_id = project_id,
        extra_context = {"p" : project}
    )

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-us" xml:lang="en-us" >
<head>
<title>Change project | Django site admin</title>
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/simple_docs.css" />
<!--link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" /-->
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/static/admin/css/ie.css" /><![endif]-->

<meta name="robots" content="NONE,NOARCHIVE" />
</head>
<body>
<div id="container">


{% block content %}
{% endblock %}

{% block footer %}
<div id="footer">
	<a href="{% url project_list %}">project list</a>
	&nbsp;|&nbsp; <a href="http://www.mcb.harvard.edu">Molecular &amp; Cellular Biology</a>
    &nbsp;&nbsp; ({% now "F jS, Y f:s a" %})
</div>
{% endblock %}

</div>

</body>
</html>

templates/project/databases.html
{% if p.databases.count > 0 %}
<h2>Databases</h2>
<p><ul>
	{% for s in p.databases.all %}
	<li><b>{{ s.name }}</b>
            <p>DB name: <b>{{ s.db_name }}</b></p>
	        <p>Server: <b>{{ s.server }}</b></p>
	        <p>Description: {{ s.description|safe }}</p>
		</li>
	{% endfor %}
</ul></p>
{% endif %}

templates/project/project_detail.html
{% extends "base.html" %}
{% load project_extras %}
{% block content %}

<div id="header_content">
<h1><span class="h1_plain">project docs:</span> {{ p.name }}</h1>
</div>

<div id="main_content">
    &gt; <a href="{% url project_list %}">back to project list</a>


<h2>Purpose</h2>
<div class="indent1">{{ p.purpose|linebreaks|safe }}</div>

{% if p.url or p.has_project_links %}
<h2>Link(s)</h2>
<ul>
	{% if p.url %}<li><a href="{{ p.url }}" target="_blank">{{ p.url }}</a></li>{% endif %}
	{% for pl in p.get_project_links %}
		<li>{{ pl.name }}: <a href="{{ pl.url }}" target="_blank">{{ pl.url }}</a></li>
	{% endfor %}
</ul>
{% endif %}

{% if p.description %}
<h2>Description</h2>
<div class="indent1">{{ p.description|mail_links|safe|linebreaks }}</div>
{% endif %}


{% if p.has_project_docs %}
<h2>Project Doc{{ p.get_project_docs|pluralize }}</h2>
<ul>
	{% for pd in p.get_project_docs %}
		<li>{{ pd.name }}: <a href="{{ pd.doc.url }}" target="_blank">{{ pd.doc.name }}</a></li>
	{% endfor %}
</ul>
{% endif %}


<h2>Contacts</h2>
<div class="indent1">{{ p.contacts|mail_links|safe|linebreaks }}</div>

{% if p.servers.count > 0 %}
<h2>Servers</h2>
<p><ul>
	{% for s in p.servers.all %}
	<li><b>{{ s.name }}</b>
		{% if s.url %} &#151; <a href="{{ s.url }}">{{ s.url }}</a>{% endif %}
		{% if s.short_description %}<p>{{ s.short_description|mail_links|safe|linebreaks  }}</p>{% endif %}
		
		</li>
	{% endfor %}
</ul></p>
{% endif %}
{% include "project/databases.html" %}

{% if p.authentication.count > 0 %}
<h2>Authentication</h2>
<p><ul>
	{% for auth in p.authentication.all %}
	<li><b>{{ auth.name }}</b>
		{% if auth.url %} &#151; <a href="{{ auth.url }}">{{ auth.url }}</a>{% endif %}
		{% if auth.description %}<p>{{ auth.description|mail_links|safe|linebreaks  }}</p>{% endif %}
		</li>
{% endfor %}
</ul></p>
{% endif %}

{% if p.codebase %}
<h2>Codebase</h2>
<div class="indent1">{{ p.codebase|linebreaks|safe }}</div>
{% endif %}

{% if p.related_projects.count > 0 %}
<h2>Related Projects</h2>
<p><ul>
{% for rl in p.related_projects.all %}
	<li><a href="{% url project_detail rl.id %}">{{ rl.name }}</a></li>
{% endfor %}
</ul>
</p>
{% endif %}

{% if p.tags.count > 0 %}
<h2>Tags</h2>
<div class="indent1">{% for t in p.tags.all %}
	{{ t }} &nbsp;
{% endfor %}
</div>
{% endif %}
</div>



{% endblock %}

templates/project/project_list.html
{% extends "base.html" %}
{% block content %}
<div id="header_content">
    <h1>Project Listing</h1>
</div>
<div id="main_content">

<p><b>project count</b>: {{ project_list.count }}
<table cellpadding="0" cellspacing="0">
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>name</th>
			<th>purpose</th>
		</tr>
	</thead>	
	{% for p in project_list %}
	 	<tr>
			<td>{{ forloop.counter }}</td>
			<td><a href="{% url project_detail p.id %}">{{ p.name }}</a></td>
			<td>{{ p.purpose }}</td>
		</tr>
	{% empty %}
		<tr>
			<td colspan="3">no projects found</td>
		</tr>
	{% endfor %}
</table>
</p>
</div>
{% endblock %}

templates/static_site/static_database_list.html
{% extends "base.html" %}
{% block content %}
<div id="header_content">
    <h1><a href="index.html">Project Listing</a>
       &nbsp;|&nbsp; Database Listing
   </h1>
</div>
<div id="main_content">
    &gt; <a href="index.html">back to project list</a>

<p><b>database count</b>: {{ database_list.count }}
<table cellpadding="0" cellspacing="0">
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>name</th>
			<th>db name</th>
			<th>description</th>
			<th>server</th>
			<th>project(s)</th>
		</tr>
	</thead>	
	{% for p in database_list %}
	 	<tr>
			<td>{{ forloop.counter }}</td>
			<td>{{ p.name }}</td>
			<td>{{ p.db_name }}</td>
			<td>{{ p.description }}</td>
			<td>{{ p.server }}</td>
			<td>{% for proj in p.project_set.all %}
			    {% if forloop.first %}<ul class="dblist">{% endif %}
			    <li><a href="{{ proj.get_html_filename }}">{{ proj.name }}</a></li>
			    {% if forloop.last %}</ul>{% endif %}
			    {% empty %}
			    n/a
			    {% endfor %}
			</td>
		</tr>
	{% empty %}
		<tr>
			<td colspan="6">no databases found</td>
		</tr>
	{% endfor %}
</table>
</p>
</div>
{% endblock %}


{% block footer %}
<div id="footer">
	<a href="index.html">project list</a>
	&nbsp;|&nbsp; <a href="http://www.mcb.harvard.edu">Molecular &amp; Cellular Biology</a>
    &nbsp;&nbsp; ({% now "F jS, Y f:s a" %})
</div>
{% endblock %}

templates/static_site/static_project_detail.html
{% extends "base.html" %}
{% load project_extras %}
{% block content %}

<div id="header_content">
<h1><span class="h1_plain">project docs:</span> {{ p.name }}</h1>
</div>

<div id="main_content">
    &gt; <a href="index.html">back to project list</a>


<h2>Purpose</h2>
<div class="indent1">{{ p.purpose|linebreaks|safe }}</div>

{% if p.url or p.has_project_links %}
<h2>Link(s)</h2>
<ul>
	{% if p.url %}<li><a href="{{ p.url }}" target="_blank">{{ p.url }}</a></li>{% endif %}
	{% for pl in p.get_project_links %}
		<li>{{ pl.name }}: <a href="{{ pl.url }}" target="_blank">{{ pl.url }}</a></li>
	{% endfor %}
</ul>
{% endif %}

{% if p.description %}
<h2>Description</h2>
<div class="indent1">{{ p.description|mail_links|safe|linebreaks }}</div>
{% endif %}


{% if p.has_project_docs %}
<h2>Project Doc{{ p.get_project_docs|pluralize }}</h2>
<ul>
	{% for pd in p.get_project_docs %}
		<li>{{ pd.name }}: <a href="{{ pd.doc.name }}" target="_blank">{{ pd.doc.name }}</a></li>
	{% endfor %}
</ul>
{% endif %}


<h2>Contacts</h2>
<div class="indent1">{{ p.contacts|mail_links|safe|linebreaks }}</div>

{% if p.servers.count > 0 %}
<h2>Servers</h2>
<p><ul>
	{% for s in p.servers.all %}
	<li><b>{{ s.name }}</b>
		{% if s.url %} &#151; <a href="{{ s.url }}">{{ s.url }}</a>{% endif %}
		{% if s.short_description %}<p>{{ s.short_description|mail_links|safe|linebreaks  }}</p>{% endif %}
		
		</li>
	{% endfor %}
</ul></p>
{% endif %}

{% include "project/databases.html" %}

{% if p.authentication.count > 0 %}
<h2>Authentication</h2>
<p><ul>
	{% for auth in p.authentication.all %}
	<li><b>{{ auth.name }}</b>
		{% if auth.url %} &#151; <a href="{{ auth.url }}">{{ auth.url }}</a>{% endif %}
		{% if auth.description %}<p>{{ auth.description|mail_links|safe|linebreaks  }}</p>{% endif %}
		</li>
{% endfor %}
</ul></p>
{% endif %}

{% if p.codebase %}
<h2>Codebase</h2>
<div class="indent1">{{ p.codebase|linebreaks|safe }}</div>
{% endif %}

{% if p.related_projects.count > 0 %}
<h2>Related Projects</h2>
<p><ul>
{% for rl in p.related_projects.all %}
	<li><a href="{{ rl.get_html_filename }}">{{ rl.name }}</a></li>
{% endfor %}
</ul>
</p>
{% endif %}

{% if p.tags.count > 0 %}
<h2>Tags</h2>
<div class="indent1">{% for t in p.tags.all %}
	{{ t }} &nbsp;
{% endfor %}
</div>
{% endif %}
</div>
{% endblock %}


{% block footer %}
<div id="footer">
	<a href="index.html">project list</a>
	&nbsp;|&nbsp; <a href="http://www.mcb.harvard.edu">Molecular &amp; Cellular Biology</a>
    &nbsp;&nbsp; ({% now "F jS, Y f:s a" %})
</div>
{% endblock %}

templates/static_site/static_project_list.html
{% extends "base.html" %}
{% block content %}
<div id="header_content">
    <h1>Project Listing
    &nbsp;|&nbsp; <a href="databases.html">Database Listing</a>
    </h1>
</div>
<div id="main_content">

<p><b>project count</b>: {{ project_list.count }}
<table cellpadding="0" cellspacing="0">
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>name</th>
			<th>purpose</th>
		</tr>
	</thead>	
	{% for p in project_list %}
	 	<tr>
			<td>{{ forloop.counter }}</td>
			<td><a href="{{ p.get_html_filename }}">{{ p.name }}</a></td>
			<td>{{ p.purpose }}</td>
		</tr>
	{% empty %}
		<tr>
			<td colspan="3">no projects found</td>
		</tr>
	{% endfor %}
</table>
</p>
</div>
{% endblock %}


{% block footer %}
<div id="footer">
	<a href="index.html">project list</a>
	&nbsp;|&nbsp; <a href="http://www.mcb.harvard.edu">Molecular &amp; Cellular Biology</a>
    &nbsp;&nbsp; ({% now "F jS, Y f:s a" %})
</div>
{% endblock %}